### ISSUE TITLE
Crashes with invalid files

### ISSUE THREAD

**Issue by qarmin** [WuBingzheng/build-lua-in-rust#1]
Broken 1221 files that cause panics - [Broken_1221.zip](https://github.com/WuBingzheng/build-lua-in-rust/files/11240606/Broken_1221.zip)

```
thread 'main' panicked at ''end' expected', src/parse.rs:704:21
thread 'main' panicked at 'assertion failed: `(left == right)`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseFloatError { kind: Invalid }', src/lex.rs:177:45
thread 'main' panicked at 'expect name', src/parse.rs:1626:13
thread 'main' panicked at 'invalid args Name("rt")', src/parse.rs:1377:18
thread 'main' panicked at 'invalid assign Add', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Eos', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign If', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Len', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Mod', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("Foo")', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("GField")', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("be")', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("cal")', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("cjson")', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("describe")', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("ese")', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("foo")', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("nter")', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("nu")', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("pi1")', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("pok")', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("prefix_hndler")', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("res")', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("self")', src/parse.rs:318:22
thread 'main' panicked at 'invalid assign Name("x")', src/parse.rs:318:22
thread 'main' panicked at 'invalid char 129', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 131', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 133', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 134', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 138', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 140', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 141', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 143', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 145', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 148', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 150', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 153', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 154', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 155', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 157', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 160', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 162', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 163', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 164', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 165', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 166', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 168', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 172', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 176', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 182', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 183', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 191', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 231', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 240', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 241', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 242', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 243', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 244', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 27', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 64', src/lex.rs:119:22
thread 'main' panicked at 'invalid char 96', src/lex.rs:119:22
thread 'main' panicked at 'invalid function: nil', src/vm.rs:882:18
thread 'main' panicked at 'invalid prefixexp End', src/parse.rs:925:18
thread 'main' panicked at 'invalid prefixexp Eos', src/parse.rs:925:18
thread 'main' panicked at 'invalid prefixexp Equal', src/parse.rs:925:18
thread 'main' panicked at 'invalid prefixexp GreEq', src/parse.rs:925:18
thread 'main' panicked at 'invalid prefixexp If', src/parse.rs:925:18
thread 'main' panicked at 'invalid prefixexp Less', src/parse.rs:925:18
thread 'main' panicked at 'invalid prefixexp Pow', src/parse.rs:925:18
thread 'main' panicked at 'invalid prefixexp SqurL', src/parse.rs:925:18
thread 'main' panicked at 'invalid string escape', src/lex.rs:224:18
thread 'main' panicked at 'invalid table Colon', src/parse.rs:1598:22
thread 'main' panicked at 'invalid table Eos', src/parse.rs:1598:22
thread 'main' panicked at 'invalid table Name("foo")', src/parse.rs:1598:22
thread 'main' panicked at 'invalid table Name("name")', src/parse.rs:1598:22
thread 'main' panicked at 'invalid table Name("x00000200")', src/parse.rs:1598:22
thread 'main' panicked at 'invalid table String([108, 111, 103, 103, 108, 121])', src/parse.rs:1598:22
thread 'main' panicked at 'no varargs', src/parse.rs:848:21
thread 'main' panicked at 'not yet implemented: long comment', src/lex.rs:273:27
thread 'main' panicked at 'not yet implemented: meta __index', src/value.rs:192:18
thread 'main' panicked at 'unfinished string', src/lex.rs:186:36
thread 'main' panicked at 'unfinished string', src/lex.rs:187:26
```

**Comment by WuBingzheng** [comment]
Thanks for your testing.

As I said in the [to be continued](https://wubingzheng.github.io/build-lua-in-rust/en/TO_BE_CONTINUED.html) chapter, this interpreter is far from complete.  I have not handled errors, and every errors panic by now! This chapter also lists the un-finished features, so you have to avoid these features while testing. There are some also [test cases](https://github.com/WuBingzheng/build-lua-in-rust/tree/main/listing/to_be_continued/test_lua).
